site_name: Cozy Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy-docs-v3
edit_uri: edit/master/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css: [css/extra.css, css/highlight_theme.css]
extra_javascript: [extra.js]
pages:
  - Home: index.md
  - Use:
    - "User guide": use/index.md
  - Synchronize:
    - 'Stay in sync': sync/index.md
    - 'Synchronize your phone': sync/phone.md
    - 'Synchronize your computer': sync/desktop.md
    - 'Install on GNU/Linux': sync/linux.md
  - Download: download/index.md
  - Install:
    - install/index.md
    - "Debian": install/debian.md
    - "Manual installation": install/manual.md
  - Develop:
    - "Let's hack some code": dev/index.md
    - "Architecture": dev/intro.md
    - "Create your first app": dev/app.md
    - "Develop a connector": dev/konnector.md
    - "Create a mobile app with cordova": dev/cordova.md
    - "How to send mail in development": dev/sendmail.md
    - References:
      - cozy-konnector-libs:
        - "API" : cozy-konnector-libs/api.md
        - "CLI": cozy-konnector-libs/cli.md
        - "Develop": cozy-konnector-libs/dev.md
        - "Errors": cozy-konnector-libs/errors.md
        - "Operation linking": cozy-konnector-libs/operation-linking.md
        - "Synchronization": cozy-konnector-libs/synchronization.md
      - cozy-client-js:
        - "Introduction": cozy-client-js/intro.md
        - "Transition from cozy-browser-sdk": cozy-client-js/browser-sdk-transition.md
        - "How to support offline": cozy-client-js/offline.md
        - "OAuth guide": cozy-client-js/oauth.md
        - "Authentication API": cozy-client-js/auth-api.md
        - "Data System API": cozy-client-js/data-api.md
        - "Files API": cozy-client-js/files-api.md
        - "Jobs API": cozy-client-js/jobs-api.md
        - "Intents API": cozy-client-js/intents-api.md
        - "Settings API": cozy-client-js/settings-api.md
        - "Sharing API": cozy-client-js/sharing-api.md
theme: mkdocs
theme_dir: 'cozy-theme'
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - footnotes
  - meta
  #- markdown_i18n:
  #    i18n_lang: en_US
  #    i18n_dir: i18n
  - sane_lists
  - smarty
  - toc:
      permalink: True
