site_name: Documentation
docs_dir: src
site_url: https://docs.cozy.io/
site_dir: docs/en
site_favicon: img/favicon.png
repo_url: https://github.com/cozy/cozy.github.io/
edit_uri: edit/dev/src/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
extra_css:
- css/extra.css
- css/highlight_theme.css
extra_javascript:
- extra.js
pages:
- Home: index.md
- Install:
  - install/index.md
  - Debian: install/debian.md
  - Manual installation: install/manual.md
- Develop:
  - Let's hack some code: dev/index.md
  - Connect a mobile app to your local stack: dev/connect-mobile-app-local-stack.md
  - Architecture: dev/intro.md
  - Create your first app: dev/app.md
  - Develop a connector: dev/konnector.md
  - Create a mobile app with cordova: dev/cordova.md
  - Git Flow: dev/git-flow.md
  - How to send mail in development: dev/sendmail.md
  - References:
    - null # This is filled automatically via add_external_docs.py
- Synchronize:
  - Install Cozy Drive on GNU/Linux: sync/linux.md
theme: mkdocs
theme_dir: cozy-theme
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - footnotes
  - meta
  - sane_lists
  - smarty
  - toc:
      permalink: True
