site_name: Cozy Documentation
site_url: http://clochix.github.io/gozy-docs/
repo_url: https://github.com/clochix/gozy-docs/
edit_uri: edit/master/docs/
site_description: Cozy documentation
site_author: CozyCloud - https://cozy.io
pages:
  - Home: index.md
  - Use:
    - "User guide": use/index.md
  - Synchronize:
    - 'Stay in sync': sync/index.md
    - 'Synchronize your phone': sync/phone.md
    - 'Synchronize your computer': sync/desktop.md
  - Install:
    - Manual: install/manual.md
  - Develop:
    - Introduction: dev/index.md
    - "Create your first app": dev/app.md
    - "Develop a connector": dev/konnector.md
theme: readthedocs
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - markdown_i18n:
      i18n_lang: en_US
      i18n_dir: i18n
  - sane_lists
  - smarty
  - toc:
      permalink: True

